version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "helloworldlambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1x1b21fhu8iek"
s3_prefix = "helloworldlambda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=976647416941.dkr.ecr.us-east-1.amazonaws.com/helloworldlambda7242e15a/helloworldfunction19d43fc4repo"]
